  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/php:apache-stretch
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run: php test.php
